name: 🧪

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        issue: 1
        approvers: |
          joshmgross
    - run: cat README.md
